all:
	g++ -std=c++11 `pkg-config --cflags opencv` Capture.cpp -o capture -ljpeg -march=nehalem `pkg-config --libs opencv`
compile:

#change directory when change folder
#-march=nehalem
#-I/home/nguyenpd-ssh/Desktop/nhomNFV-camxoa/24-2-2019/9002/decodeGray
