all:
	g++ -std=c++11 `pkg-config --cflags opencv` density.cpp  senDensity.cpp -o sendensity -ljpeg -march=nehalem `pkg-config --libs opencv`
compile:
#add -mfpu=neon for RaspberryPi
#chANGE directory when change folder
